/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Estudiante
 */
import java.io.*;
import java.util.*;
import javax.swing.*;

public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbliniciales = new javax.swing.JLabel();
        btnencontrar = new javax.swing.JButton();
        lblres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstiniciales = new javax.swing.JList<>();
        lblnombres = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstnombres = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciales");

        lbliniciales.setText("Encuentra las iniciales en el txt");

        btnencontrar.setText("Encontrar");
        btnencontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencontrarActionPerformed(evt);
            }
        });

        lblres.setText("Resultado:");

        jScrollPane1.setViewportView(lstiniciales);
        lstiniciales.getAccessibleContext().setAccessibleParent(lstiniciales);

        lblnombres.setText("Nombres:");

        jScrollPane2.setViewportView(lstnombres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblnombres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblres)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnencontrar))
                            .addComponent(lbliniciales))
                        .addGap(93, 93, 93))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbliniciales)
                .addGap(18, 18, 18)
                .addComponent(btnencontrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblres)
                    .addComponent(lblnombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnencontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencontrarActionPerformed
        // TODO add your handling code here:
        String linea = "";
        ArrayList<String> lineas = new ArrayList<String>();
        String archivo = "C:\\Users\\vergo_000\\Desktop\\Guia 1 de POO\\Ejercicio2_LuisBernal\\src\\iniciales.txt";
        File file = new File(archivo);
        try {
            FileReader fr = new FileReader(archivo);
            BufferedReader bf = new BufferedReader(fr);
            DefaultListModel modelo,modelo2;
            modelo = new DefaultListModel();
            modelo2=new DefaultListModel();
            try {
                int in = 0;
                while (null != linea) {
                    linea = bf.readLine();
                    lineas.add(linea);
                    in++;
                }
                Object[] obj = lineas.toArray();
                String[] separacion = Arrays.copyOf(obj, obj.length, String[].class);
                for (int i = 0; i < separacion.length - 1; i++) {
                    String fin = "";
                    String[] ggwp = separacion[i].split(" ");
                    for (int i2 = 0; i2 < ggwp.length; i2++) {
                        fin = fin.concat(ggwp[i2].substring(0, 1));
                    }
                    modelo2.addElement(separacion[i]);
                    modelo.addElement(fin);
                }

                lstiniciales.setModel(modelo);
                lstnombres.setModel(modelo2);
                lineas.clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error al abrir el archivo");
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al abrir el archivo");
        }


    }//GEN-LAST:event_btnencontrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnencontrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbliniciales;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblres;
    private javax.swing.JList<String> lstiniciales;
    private javax.swing.JList<String> lstnombres;
    // End of variables declaration//GEN-END:variables
}
